# yaml-language-server: $schema=https://json.schemastore.org/travis.json
language: generic
sudo: required
dist: jammy

services:
  - docker

before_install:
  - docker build -t docker-react-dev -f Dockerfile.dev .

script:
  - docker run -e CI=true docker-react-dev pnpm test -- --watchAll=false --coverage
  - docker build -t docker-react-prod .

notifications:
  email:
    on_success: change
    on_failure: always
