# yaml-language-server: $schema=https://json.schemastore.org/travis.json
sudo: required

services:
  - docker

before_install:
  - docker build -t docker-react-dev -f Dockerfile.dev .

script:
  - docker run -e CI=true docker-react-dev pnpm test -- --coverage #--watchAll=false
  - docker build -t docker-react-prod .
