# yaml-language-server: $schema=https://json.schemastore.org/travis.json
language: generic
sudo: required
dist: jammy

services:
  - docker

before_install:
  - docker build -t docker-react-dev -f Dockerfile.dev .

script:
  - docker run -e CI=true docker-react-dev pnpm test --watchAll=false --coverage
  - docker build -t docker-react-prod .

deploy:
  provider: elasticbeanstalk
  region: ap-northeast-1
  app: docker-next
  env: Docker-Next-env
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: elasticbeanstalk-ap-northeast-1-207108708768
  bucket_path: docker-next
  edge: true # opt in to dpl v2
  on:
    branch: main

notifications:
  email:
    on_success: never
    on_failure: always
